In [3]:
import torch

In [11]:
x = torch.rand(1, 10, dtype=torch.float32) * 100
y = x.to(torch.float16)
z = x.to(torch.torch.float8_e4m3fn)
print(x)
print(y)
print(z)

tensor([[19.4150, 74.0398, 25.0154, 43.8534, 35.3257, 38.6901, 78.4495, 30.3837,
         27.5394, 47.9332]])
tensor([[19.4219, 74.0625, 25.0156, 43.8438, 35.3125, 38.6875, 78.4375, 30.3906,
         27.5469, 47.9375]], dtype=torch.float16)
tensor([[20., 72., 26., 44., 36., 40., 80., 30., 28., 48.]],
       dtype=torch.float8_e4m3fn)
