In [2]:
import torch

In [39]:
x = torch.rand(1, 10, dtype=torch.float32)
y = x.to(torch.float16)
z = x.to(torch.torch.float8_e4m3fn).to(torch.float16)
print(x)
print(y)
print(z)

tensor([[0.4198, 0.6680, 0.2828, 0.5417, 0.3321, 0.2249, 0.9567, 0.6113, 0.0896,
         0.3476]])
tensor([[0.4199, 0.6680, 0.2830, 0.5415, 0.3320, 0.2249, 0.9565, 0.6113, 0.0897,
         0.3477]], dtype=torch.float16)
tensor([[0.4062, 0.6875, 0.2812, 0.5625, 0.3438, 0.2188, 0.9375, 0.6250, 0.0859,
         0.3438]], dtype=torch.float16)


In [35]:
x = torch.tensor([[48.7218, 62.6936, 26.1018, 33.3768, 26.7844, 37.2599, 77.4297, 94.0653,67.0340, 96.7653]])
y = x.to(torch.float16)
z = x.to(torch.torch.float8_e4m3fn).to(torch.float16)
print(x)
print(y)
print(z)

tensor([[48.7218, 62.6936, 26.1018, 33.3768, 26.7844, 37.2599, 77.4297, 94.0653,
         67.0340, 96.7653]])
tensor([[48.7188, 62.6875, 26.1094, 33.3750, 26.7812, 37.2500, 77.4375, 94.0625,
         67.0625, 96.7500]], dtype=torch.float16)
tensor([[48., 64., 26., 32., 26., 36., 80., 96., 64., 96.]],
       dtype=torch.float16)
